import type { Market } from "./types"

export const MARKETS: Market[] = [
  {
    id: "minnetonka-roofing",
    city: "Minnetonka",
    region: "MN",
    brand: "Storm Master Roofing",
    accountId: "acc_stormmaster_mn",
    vertical: "Roofing",
    rating: 4.9,
    reviews: 180,
    queries: [
      "roofing contractor",
      "storm damage roof repair",
      "insurance claim roofing",
      "emergency roof repair",
      "siding contractor",
    ],
    neighborhoods: [
      "Minnetonka center",
      "North Minnetonka",
      "South Minnetonka",
      "Glen Lake",
      "Deephaven",
      "Woodland",
      "Greenwood",
      "Shorewood",
      "Excelsior",
      "Tonka Bay",
      "Wayzata",
      "Plymouth",
      "Medicine Lake",
      "New Hope",
      "Golden Valley",
      "St Louis Park",
      "Hopkins",
      "Minnetonka Mills",
      "Eden Prairie",
      "Chanhassen",
      "Orono",
      "Long Lake",
      "Maple Grove",
      "Edina west",
      "Minnetrista",
    ],
    competitors: [
      "Lehmann Roofing",
      "All Seasons Roofing MN",
      "Premier Roofing LLC",
      "Minnetonka Exterior Pros",
      "Twin Cities Roof Co",
      "Northland Roofing",
    ],
  },
  {
    id: "austin-hvac",
    city: "Austin",
    region: "TX",
    brand: "Northstar Mechanical",
    accountId: "acc_northstar_tx",
    vertical: "HVAC",
    rating: 4.8,
    reviews: 412,
    queries: [
      "emergency ac repair",
      "ac repair near me",
      "same day hvac",
      "furnace repair",
      "ac installation",
    ],
    neighborhoods: [
      "Downtown",
      "Zilker",
      "South Lamar",
      "Barton Hills",
      "Clarksville",
      "East Austin",
      "Mueller",
      "Hyde Park",
      "Crestview",
      "Allandale",
      "The Domain",
      "North Loop",
      "Cherrywood",
      "Riverside",
      "Oak Hill",
      "Round Rock",
      "Pflugerville",
      "Cedar Park",
      "Lakeway",
      "Manor",
      "Buda",
      "Kyle",
      "Westlake",
      "Sunset Valley",
      "Brentwood",
    ],
    competitors: [
      "CoolAir Pros",
      "Atlas Climate",
      "Lone Star Mechanical",
      "Hill Country Air",
      "Rapid Response HVAC",
      "Capital City Cooling",
    ],
  },
  {
    id: "phoenix-plumbing",
    city: "Phoenix",
    region: "AZ",
    brand: "Redline Rooter",
    accountId: "acc_redline_az",
    vertical: "Plumbing",
    rating: 4.7,
    reviews: 288,
    queries: [
      "emergency plumber",
      "drain cleaning near me",
      "water heater repair",
      "burst pipe",
      "sewer line",
    ],
    neighborhoods: [
      "Downtown",
      "Arcadian",
      "Central City",
      "Willo",
      "Encanto",
      "Roosevelt",
      "Melrose",
      "Alhambra",
      "Sunbury",
      "Maryvale",
      "Ahwatukee",
      "Desert Ridge",
      "North Mountain",
      "Paradise Valley",
      "Deer Valley",
      "Glendale",
      "Mesa",
      "Tempe",
      "Scottsdale",
      "Chandler",
      "Gilbert",
      "Peoria",
      "Avondale",
      "Goodyear",
      "Surprise",
    ],
    competitors: [
      "Desert Pipe Co",
      "Valley Rooter",
      "Superstition Plumbing",
      "Red Rock Drain",
      "Camelback Mechanical",
      "Salt River Plumbing",
    ],
  },
  {
    id: "miami-roofing",
    city: "Miami",
    region: "FL",
    brand: "Harborline Roofing",
    accountId: "acc_harborline_fl",
    vertical: "Roofing",
    rating: 4.9,
    reviews: 356,
    queries: [
      "roof leak repair",
      "emergency roofing",
      "tile roof repair",
      "hurricane roof",
      "roof replacement",
    ],
    neighborhoods: [
      "Brickell",
      "Downtown",
      "Wynwood",
      "Design District",
      "Little Havana",
      "Coconut Grove",
      "Coral Gables",
      "Key Biscayne",
      "Edgewater",
      "Midtown",
      "Little Haiti",
      "Allapattah",
      "Flagami",
      "Westchester",
      "Kendall",
      "Doral",
      "Hialeah",
      "Miami Beach",
      "North Miami",
      "Homestead",
      "Cutler Bay",
      "Pinecrest",
      "Aventura",
      "Sweetwater",
      "Olympia Heights",
    ],
    competitors: [
      "Tideline Roofing",
      "Coral Gables Cover",
      "Stormproof Miami",
      "Palmetto Roof Co",
      "Biscayne Exteriors",
      "Atlantic Deck",
    ],
  },
]

export function marketById(id: string): Market {
  const found = MARKETS.find((m) => m.id === id)
  if (!found) throw new Error(`Unknown market: ${id}`)
  return found
}
